### ISSUE TITLE
Fix warning "Warning: Each child in a list should have a unique "key" prop" in ProposalRow.tsx

### ISSUE THREAD

**Issue by sardariuss** [sardariuss/CyclesDAO#8]

**Comment by jwardoin** [comment]
Having trouble getting my local env setup to test, but simply adding key={some value} to each li element should fix this error. Happy to complete this and open a PR if you'd like

**Comment by sardariuss** [comment]
Hey Jordan, thanks for the proposal! Yeah I tried to set a key but
it didn't work, but maybe I'm not doing it correctly. I'd be happy if you
manage to do it!

**Comment by jwardoin** [comment]
Were the keys you entered different for each li? Having the same key on two or more will also give you this warning

**Comment by sardariuss** [comment]
Well I thi k they are yes

**Comment by sardariuss** [comment]
Solved. It was because the key was in a child element of the row, not the top (parent) element.
